CREATE TABLE IF NOT EXISTS suppliers (
  id CHAR(36) NOT NULL PRIMARY KEY,
  organization_id CHAR(36) NOT NULL,
  name VARCHAR(255) NOT NULL,
  code VARCHAR(128) NULL,
  contact_email VARCHAR(320) NULL,
  contact_phone VARCHAR(128) NULL,
  website VARCHAR(2048) NULL,
  city VARCHAR(128) NULL,
  state VARCHAR(128) NULL,
  country VARCHAR(128) NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_approved BOOLEAN NOT NULL DEFAULT FALSE,
  erp_id VARCHAR(255) NULL,
  erp_synced_at DATETIME(3) NULL,
  created_by CHAR(36) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_suppliers_org_code (organization_id, code),
  INDEX idx_suppliers_org_active_name (organization_id, is_active, name),
  CONSTRAINT fk_supplier_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_supplier_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS part_suppliers (
  id CHAR(36) NOT NULL PRIMARY KEY,
  organization_id CHAR(36) NOT NULL,
  file_id CHAR(36) NOT NULL,
  supplier_id CHAR(36) NOT NULL,
  supplier_part_number VARCHAR(255) NULL,
  supplier_description TEXT NULL,
  supplier_url VARCHAR(2048) NULL,
  unit_price DECIMAL(18,6) NULL,
  currency CHAR(3) NOT NULL DEFAULT 'USD',
  price_unit VARCHAR(64) NOT NULL DEFAULT 'each',
  price_breaks JSON NULL,
  min_order_qty INT NULL DEFAULT 1,
  order_multiple INT NULL DEFAULT 1,
  lead_time_days INT NULL,
  is_preferred BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  is_qualified BOOLEAN NOT NULL DEFAULT FALSE,
  qualified_at DATETIME(3) NULL,
  notes TEXT NULL,
  last_price_update DATETIME(3) NULL,
  created_by CHAR(36) NOT NULL,
  updated_by CHAR(36) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_part_suppliers_file_supplier (file_id, supplier_id),
  INDEX idx_part_suppliers_file_active (file_id, is_active, is_preferred),
  CONSTRAINT fk_part_supplier_org FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE,
  CONSTRAINT fk_part_supplier_file FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE,
  CONSTRAINT fk_part_supplier_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT,
  CONSTRAINT fk_part_supplier_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_part_supplier_updater FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
